### ISSUE TITLE
Failure: No module named 'aiogram'

### ISSUE THREAD

**Issue by balupton** [XayOn/katcr#145]
```
> python3 -m pipx install --include-deps --force katcr
Installing to existing venv 'katcr'
⚠️  Note: chardetect was already on your PATH at /usr/bin/chardetect
  installed package katcr 3.0.7, Python 3.9.5
  These apps are now globally available
    - bot
    - chardetect
    - gogo
    - katcr
    - normalizer
    - py.test
    - pytest
    - tabulate
    - torrentmirror
    - yapf
done! ✨ 🌟 ✨

> katcr search 'big buck bunny'
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/katcr", line 5, in <module>
    from katcr import main
  File "/home/ubuntu/.local/pipx/venvs/katcr/lib/python3.9/site-packages/katcr/__init__.py", line 24, in <module>
    from .bot import BotHandler
  File "/home/ubuntu/.local/pipx/venvs/katcr/lib/python3.9/site-packages/katcr/bot.py", line 1, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
```

**Expected behavior**
It to work.

**Desktop (please complete the following information):**
 - OS: `Linux raspi8 5.11.0-1021-raspi #22-Ubuntu SMP PREEMPT Wed Oct 6 17:30:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
 - Version `katcr 3.0.7, Python 3.9.5`

**Comment by balupton** [comment]
`python3 -m pip install aiogram` seems to have resolved it.... however the results of `katcr search` are being returned in HTML....

**Comment by XayOn** [comment]
That's interesting. 
I don't use pipx myself, I use plain pip. Aiogram is declared on pyproject.toml as both an optional dep and a normal one, because it's only actually used for the bot. Could you try to install katcr[bot]?
Trying a "plain pip" install and reporting the results could also help with this issue, thanks.


Could you add an example on what you mean by html results? I just tested last version and it doesn't seem to be broken (sometimes, some provider breaks and causes issues... but doesn't seem to be the case)

[☛]Debian Recovery Tool v1.0
[ ] Aleks Linux Debian CORE (2012) [Multilanguaje]
[ ] LimeWire PRO v5.1.2 Final Linux (Ubuntu, Debian) By ChattChitto
[ ] Ubuntu Linux Toolbox 1000+ Commands for Ubuntu and Debian Power
[ ] How Skolelinux works (Debian Edu) - Speech by Anders Kringstad
[ ] Debian 7- System Administration Best Practices, 2013 [PDF]~Storm
[ ] Manuales varios Debian
