### ISSUE TITLE
Error when installing via pip on windows

### ISSUE THREAD

**Issue by benunderw** [XayOn/katcr#45]
Hi there! I'm running into this odd error when installing the project via pip 10.0.0 / python 3.6, any idea what's going on?

```Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>pip install katcr
Collecting katcr
  Using cached https://files.pythonhosted.org/packages/83/d2/0a2187fb01d650d6cdf5fce4056fdc603d3e09b6aefd3e97420b2cd491f0/katcr-1.0.5.tar.gz
Requirement already satisfied: docopt==0.6.2 in c:\users\ben\appdata\local\programs\python\python36\lib\site-packages (from katcr) (0.6.2)
Requirement already satisfied: requests==2.18.4 in c:\users\ben\appdata\local\programs\python\python36\lib\site-packages (from katcr) (2.18.4)
Collecting inquirer==2.2.0 (from katcr)
  Using cached https://files.pythonhosted.org/packages/bd/b8/0b04f23f7870f96c81bdf9b9863c12985bec0f2738218bcfc67842be4ae8/inquirer-2.2.0-py2.py3-none-any.whl
Collecting telepot==12.3 (from katcr)
  Using cached https://files.pythonhosted.org/packages/9e/bd/8c363b54c38498d8ab93daf4dde1d3b0bc8f1d8c8b692151aff8ec7eb8a2/telepot-12.3.tar.gz
Collecting robobrowser==0.5.3 (from katcr)
  Using cached https://files.pythonhosted.org/packages/f3/53/fd527e78fe8bdf7ec24b3b821c88c2dcbbe63d120c838f80f12ed0a0fac6/robobrowser-0.5.3.tar.gz
Collecting torrentmirror==0.0.1.dev5 (from katcr)
  Using cached https://files.pythonhosted.org/packages/a9/c2/e139d5be8a8fda4a11dfbc281612038b48d783c6fc9e48267d470bf6159f/torrentmirror-0.0.1.dev5.tar.gz
Collecting tableprint==0.7.0 (from katcr)
  Using cached https://files.pythonhosted.org/packages/3e/48/87c912139e061e2c075386668a5c47090ee5f9f3ab861f7fc4fececd485b/tableprint-0.7.0.tar.gz
Collecting pygogo==0.10.0 (from katcr)
  Using cached https://files.pythonhosted.org/packages/1f/cd/789ba0528ec5839078267611cfa1bc2be124a09a061a144c53c2b2e0aaeb/pygogo-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\ben\appdata\local\programs\python\python36\lib\site-packages (from requests==2.18.4->katcr) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\ben\appdata\local\programs\python\python36\lib\site-packages (from requests==2.18.4->katcr) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ben\appdata\local\programs\python\python36\lib\site-packages (from requests==2.18.4->katcr) (2017.11.5)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\ben\appdata\local\programs\python\python36\lib\site-packages (from requests==2.18.4->katcr) (2.6)
Collecting blessings>=1.6 (from inquirer==2.2.0->katcr)
  Using cached https://files.pythonhosted.org/packages/2e/e8/3b7eae26b1ef0b79bfe07af1abd96586031c89b18066bd0efbb73be2f788/blessings-1.6.1-py3-none-any.whl
Collecting readchar==0.7 (from inquirer==2.2.0->katcr)
  Using cached https://files.pythonhosted.org/packages/61/a9/d552ab5bb2978b609a0acc917427fb0230ac923d92e32b817ef79908f6e3/readchar-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ben\AppData\Local\Temp\pip-install-m13zes8s\readchar\setup.py", line 15, in <module>
        long_description=read_description(),
      File "C:\Users\Ben\AppData\Local\Temp\pip-install-m13zes8s\readchar\setup.py", line 9, in read_description
        return fd.read()
      File "c:\users\ben\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2462: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Ben\AppData\Local\Temp\pip-install-m13zes8s\readchar\

C:\WINDOWS\system32>pip --version
pip 10.0.0 from c:\users\ben\appdata\local\programs\python\python36\lib\site-packages\pip (python 3.6)

C:\WINDOWS\system32>python --version
Python 3.6.3
```

**Comment by XayOn** [comment]
@benunderw Could you please try 2.0.0?
It's been rewritten, uses poetry for package generation now and different deps
